services:
  hackacode-3-backend:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      CORS_ALLOWED_MAPPING: ${CORS_ALLOWED_MAPPING}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
